PCH_USER = "IVAN"
PCH_PATH_TO_KEY = "C:\\Users\\Public\\Documents"
PCH_PIN_CODE = "9306"
YOUR_LAST_PASSWORD = "1234qwer"
MAX_PASSWORD_LEN = 16
WAIT_TIME = 60
KEY_FILE_NAME = "password_key"
KEYWORDS = []
